### PR TITLE
fix: Permit two-word top-level collections in the URI suffix.

### LINKED ISSUE #622: AIP-136. Custom methods: URI suffix. False Detection
I have method like this one. I have a *collection* of users that should be populated from the external source "google users":
```
  rpc SyncGoogleUsers(google.protobuf.Empty) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/v1/users:syncGoogleUsers"
      body: "*"
    };
  }
```

It leads to false detection when a custom method for the whole collection instead of an item from this collection and this item has similar name `User` vs `GoogleUser`.

```
problems:
  - message: Custom method should have a URI suffix matching the method name, such as "users:sync".
    location:
      start_position:
        line_number: 34
        column_number: 5
      end_position:
        line_number: 37
        column_number: 6
    rule_id: core::0136::http-uri-suffix
    rule_doc_uri: https://linter.aip.dev/136/http-uri-suffix
```

### PR DESCRIPTION
**Pull request by lukesneeringer**
Another tweak to the perpetually-difficult `http-uri-suffix` rule from AIP-136.

Fixes #622.

### CODE REVIEW

File: rules/aip0136/http_uri_suffix_test.go [hunk 1]
```diff
@@ -27,6 +27,7 @@ func TestURISuffix(t *testing.T) {
 		URI        string
 		problems   testutils.Problems
 	}{
+		{"ValidTwoWordNoParent", "SearchAudioBooks", "/v1/audioBooks:search", nil},
```
Comment (noahdietz) [inline rules/aip0136/http_uri_suffix_test.go:30]: Nit: Why `nil` instead of `testutils.Problems{}` like all of the other `Valid` tests?

**Review by noahdietz — APPROVED** [review]
One nit but LGTM

File: rules/aip0136/http_uri_suffix_test.go (hunk 1 above)
Comment (lukesneeringer) [reply rules/aip0136/http_uri_suffix_test.go:30]: I have been shifting toward `nil` of late. At some point I will change them all.
