### PR TITLE
fix: BatchGet rule now singularizes correctly.

### LINKED ISSUE #575: AIP 231's response-resource-field does not recognize matches as the plural of match.
message BatchGetMatchesResponse {
  repeated Match matches = 1;
}

That gets flagged with this error:
Message "BatchGetMatchesResponse" has no "Matche" type field

### PR DESCRIPTION
**Pull request by lukesneeringer**
Fixes #575.

### CODE REVIEW

**Comment by lukesneeringer** [comment]
@noahdietz: I am out today, so please just merge this on my behalf (assuming you approve/agree).

File: rules/aip0231/response_resource_field.go [hunk 1]
```diff
@@ -31,7 +31,8 @@ var resourceField = &lint.MessageRule{
 		// Note: Use m.GetName()[8 : len(m.GetName())-9] to retrieve the resource
 		// name from the the batch get response, for example:
 		// "BatchGetBooksResponse" -> "Books"
-		resourceMsgName := pluralize.NewClient().Singular(m.GetName()[8 : len(m.GetName())-9])
+		plural := m.GetName()[8 : len(m.GetName())-8]
```
Comment (noahdietz) [inline rules/aip0231/response_resource_field.go:34]: The comment is helpful, but why not use `strings.TrimPrefix(n, "BatchGet")` and `strings.TrimSuffix(n, "Response")`? It would end up being more than one line, but it would be more readable and we wouldn't need magic numbers or such a detailed comment. I think the magic number was part of the cause of this bug too anyways.

File: rules/aip0231/response_resource_field.go [hunk 2]
```diff
@@ -31,7 +31,8 @@ var resourceField = &lint.MessageRule{
 		// Note: Use m.GetName()[8 : len(m.GetName())-9] to retrieve the resource
```
Comment (noahdietz) [inline rules/aip0231/response_resource_field.go:31]:
```suggestion
		// Note: Use m.GetName()[8 : len(m.GetName())-8] to retrieve the resource
```

Comment doesn't match the implementation.

File: rules/aip0231/response_resource_field.go (hunk 1 above)
Comment (lukesneeringer) [reply rules/aip0231/response_resource_field.go]: Fair point. Done.

File: rules/aip0231/response_resource_field.go (hunk 2 above)
Comment (lukesneeringer) [reply rules/aip0231/response_resource_field.go]: No longer relevant.
