### PR TITLE
fix: Permit top-level resources to have batch methods.

### LINKED ISSUE #599: aip-133: request-parent-required fires for a top-level resource
I see the error https://linter.aip.dev/133/request-parent-required for a top-level resource. https://google.aip.dev/133 states "A parent field must be included unless the resource being created is a top-level resource."

Is this a bug with the linter, or is there some way I should I be tagging my top level resources? To reproduce the error create a file `file.proto` with the following content:

```proto
syntax = "proto3";

import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";

// Service to manage Books.
service BookService {
  // Creates a new book.
  rpc CreateBook(CreateBookRequest) returns (Book) {
    option (google.api.http) = {
      post: "/v1/books"
      body: "book"
    };
    option (google.api.method_signature) = "book";
  }
}

// Request for BookService.CreateBook.
message CreateBookRequest {
  // The book to create.
  Book book = 2 [(google.api.field_behavior) = REQUIRED];
}

// Book.
message Book {
  option (google.api.resource) = {
    type: "foo.com/Book"
    pattern: "books/{book}"
  };

  // Resource name of the book.
  string name = 1;
}
```

and run the api-linter to see the following problems:

```
$ api-linter file.proto
- file_path: file.proto
  problems:
  - message: The method signature for Create methods should be "parent,book".
    suggestion: option (google.api.method_signature) = "parent,book";
    location:
      start_position:
        line_number: 16
        column_number: 5
      end_position:
        line_number: 16
        column_number: 50
    rule_id: core::0133::method-signature
    rule_doc_uri: https://linter.aip.dev/133/method-signature
  - message: Create methods should include the `parent` field in the URI.
    location:
      start_position:
        line_number: 11
        column_number: 3
      end_position:
        line_number: 17
        column_number: 3
    rule_id: core::0133::http-uri-parent
    rule_doc_uri: https://linter.aip.dev/133/http-uri-parent
  - message: Message "CreateBookRequest" has no `parent` field
    location:
      start_position:
        line_number: 21
        column_number: 1
      end_position:
        line_number: 24
        column_number: 1
    rule_id: core::0133::request-parent-required
    rule_doc_uri: https://linter.aip.dev/133/request-parent-required
```

### LINKED ISSUE #615: Update lints for parent-less batch methods
Now that https://github.com/aip-dev/google.aip.dev/issues/599 is fixed, we should update the following lints to account for the optional `parent` field:
- https://linter.aip.dev/136/http-uri-suffix
- https://linter.aip.dev/231/http-uri-suffix
- https://linter.aip.dev/231/request-parent-field
- https://linter.aip.dev/233/http-uri-suffix
- https://linter.aip.dev/233/request-parent-field
- https://linter.aip.dev/234/http-uri-suffix
- https://linter.aip.dev/234/request-parent-field

### PR DESCRIPTION
**Pull request by lukesneeringer**
Also, I rewrote the tests for these rules from scratch, as they
were in a weird state.

Fixes #615.

### CODE REVIEW

File: rules/aip0231/request_parent_field.go [hunk 1]
```diff
@@ -16,17 +16,41 @@ package aip0231
...
+			if paged := resp.FindFieldByName(strcase.SnakeCase(plural)); paged != nil {
+				if resource := utils.GetResource(paged.GetMessageType()); resource != nil {
+					for _, pattern := range resource.GetPattern() {
+						if strings.Count(pattern, "{") == 1 {
+							return false
+						}
+					}
+				}
+			}
+		}
```
Comment (noahdietz) [inline rules/aip0231/request_parent_field.go:50]: Can this logic (which is used for BatchGet, BatchCreate, and BatchUpdate) be pulled out into a function that takes the "batching method type" as param i.e. `"BatchGet"`, as well as the necessary proto input i.e. `m *desc.MessageDescriptor`? This code is non-trivial and used in three places, feels ripe for a `func`. WDYT? If there is a nuance in the code for each that prevents this that I missed, lmk.

Comment (lukesneeringer) [reply rules/aip0231/request_parent_field.go:50]: It _can_ be, although the code is slightly different each time, and I am not sure there is a good place to put it. I do not know that it is common enough to justify going in `utils`. This is right in the sour spot where the function can not be in the AIP modules themselves, but are not generic enough for me to be convinced that they belong in utils.

Comment (noahdietz) [reply rules/aip0231/request_parent_field.go:50]: Ok, I understand. Bummer!

**Review by noahdietz — APPROVED** [review]
