### PR TITLE
fix(AIP-214): scope resource-expiry to resources

### LINKED ISSUE #1073: AIP-214: resource-expiry check should only apply to resource messages
The current check for the `resource-expiry` rule will run on any message with a field named `expire_time`. This isn't as targeted as the AIP is, which applies to resource messages. Using `expire_time` in a response message, for example, should be fine without being linted. The `OnlyIf` should likely check if the parent message is a Resource as well if the field is named `expire_time`.

### PR DESCRIPTION
**Pull request by toumorokoshi**
Only resources need the API-214 resource-expiry check.

fixes #1073

### CODE REVIEW

File: rules/aip0214/resource_expiry.go [hunk 1]
```diff
@@ -23,7 +23,14 @@ import (
...
 	OnlyIf: func(f *desc.FieldDescriptor) bool {
-		return f.GetName() == "expire_time"
+		// only return true if the parent is a resource
+		if utils.GetResourceFromDescriptor(f.GetParent()) == nil {
+			return false
+		}
+		if f.GetName() != "expire_time" {
+			return false
+		}
+		return true
```
Comment (noahdietz) [inline rules/aip0214/resource_expiry.go:33]:
```suggestion
		isResource := utils.GetResourceFromDescriptor(f.GetParent()) != nil
		isExpireTime := f.GetName() == "expire_time"
		return isResource && isExpireTime
```

Kind of a nit, more my preference: It is easier to understand what the conditions are when testing for the positive case i.e. "Lint this only if parent is a resource and the field name is expire_time"

File: rules/internal/utils/extension.go [hunk 2]
```diff
@@ -104,6 +104,20 @@ func GetResource(m *desc.MessageDescriptor) *apb.ResourceDescriptor {
 	return nil
 }
 
+// GetResourceFromDescriptor returns the google.api.resource from
+// an arbitrary descriptor. If the descriptor is not a message descriptor,
+// nil is returned.
+func GetResourceFromDescriptor(d desc.Descriptor) *apb.ResourceDescriptor {
```
Comment (noahdietz) [inline rules/internal/utils/extension.go:110]: We probably don't need this actually, at least not for this use case.

The parent of a Field will always be a Message, so it is safe (and reasonable to `panic`) if the `desc.Descriptor` from `f.GetParent()` is not a `*desc.MessageDescriptor`.

So I would actually just use  something like `utils.IsResource((f.GetParent()).(*desc.MessageDescriptor))` instead of a `nil` comparison check with this.

File: rules/aip0214/resource_expiry.go (hunk 1 above)
Comment (toumorokoshi) [reply rules/aip0214/resource_expiry.go:33]: I prefer the other case slightly (guard conditions are a little easier to follow for me), but not strong enough that I won't take your suggestion. Thanks!

File: rules/internal/utils/extension.go (hunk 2 above)
Comment (toumorokoshi) [reply rules/internal/utils/extension.go]: sure, sounds good.

**Review by noahdietz — APPROVED** [review]
